/** Rebuild-in-progress marker for demo + CI. Bump when a phase lands. */
export const SHEET_MAP_REBUILD_PHASE = 5 as const;

export {
  areMapPaddingOptionsEqual,
  type ComputeCameraViewportOptions,
  computeCameraOffset,
  computeCameraViewport,
  computeMapPadding,
  createInitialMapAnchorState,
  createInitialMapFollowState,
  type FlyToMapAnchorOptions,
  flyToMapAnchor,
  isAtMapAnchorPosition,
  jumpToMapAnchor,
  type MapAnchorEvent,
  type MapAnchorFollowOptions,
  type MapAnchorSession,
  type MapAnchorState,
  type MapFollowEvent,
  type MapFollowState,
  type MapPaddingOptions,
  type MapPosition,
  type MapUserLocationCoords,
  type NavigateToMapAnchorOptions,
  positionKey,
  type ReadVisibleMapCenterOptions,
  readMapAnchorPosition,
  readVisibleMapCenterLngLat,
  reduceMapAnchor,
  reduceMapFollow,
  sampleVisibleMapPosition,
  USER_LOCATION_FOLLOW_THRESHOLD_PX,
  type UseMapAnchorOptions,
  type UseMapFollowUserOptions,
  type UseMapPaddingSyncOptions,
  useMapAnchor,
  useMapFollowUser,
  useMapPaddingSync,
  userLocationCenterDistancePx,
} from "./camera";
export {
  MAP_CANVAS_ROOT_CLASS,
  MapCanvas,
  type MapCanvasProps,
  MapInstanceProvider,
  MapInstancePublisherLayer,
  MapMyLocationButton,
  type MapMyLocationButtonProps,
  MapUserLocation,
  type MapUserLocationProps,
  type PublishMapInstance,
  resolveMapRef,
} from "./canvas";
export {
  MAP_SHELL_CLASS,
  MAP_VIEWPORT_CLASS,
  type MapBottomChromeReserve,
  MapFrame,
  type MapFrameProps,
  MapSheetLayout,
  type MapSheetLayoutProps,
} from "./shell";
export {
  areMapViewportsEqual,
  type MapCanvasScreenGeometry,
  type MapObscuredInsets,
  type MapViewportSyncState,
  MapVisibleAreaDebug,
  type MapVisibleAreaDebugProps,
  MapVisibleAreaOverlay,
  type MapVisibleViewport,
  obscuredInsetsFromScreenGeometry,
  type PixelPoint,
  type PixelRect,
  type PixelSize,
  type ResolveMapVisibleViewportOptions,
  readLiveSheetObscuredBottomPx,
  readMapCanvasScreenGeometry,
  readSheetHost,
  resolveMapVisibleViewport,
  SHEET_HOST_CLASS,
  SHEET_SLIDE_CLASS,
  type SheetSnapHeightsPx,
  type UseLiveSheetObscuredBottomPxResult,
  type UseMapVisibleViewportSyncOptions,
  type UseVisibleViewportSyncOptions,
  useLiveSheetObscuredBottomPx,
  useMapVisibleViewportSync,
  useVisibleViewportSync,
  visibleClientRectFromLiveSheetObscured,
  visibleClientRectFromScreenGeometry,
  visibleViewboxCenter,
} from "./viewport";
